[devshell]
name = "dhall-docker-compose"
packages = [
  "alejandra",
  "dhall-json",
  "dhall-lsp-server",
  "dhall",
  "dprint",
  "nixpkgs-fmt",
  "treefmt",
]

[[commands]]
package = "treefmt"
category = "formatter"

[[commands]]
name = "generate"
command = "cat docker-compose.dhall | dhall-to-yaml"
