[devshell]
name = "dhall-docker-compose"
packages = [
  "dhall",
  "treefmt",
  "nixpkgs-fmt",
  "taplo-cli",
  "dhall-json",
]

[[commands]]
name = "format"
help = "format files"
command = "treefmt"
